name: CI — Build & Test

on:
  push:
    branches:
      - lydevtech

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Java + cache Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # 3. Build + tests
      - name: Build and test
        run: mvn clean package